### ISSUE TITLE
There is no password field in parameters of connection

### ISSUE THREAD

**Issue by AlexanderKozhevin** [mlasevich/PyRSMQ#2]

**Comment by mlasevich** [comment]
Please check out the documentation in the front page :-)

Short of it - you have two options:

1 - create your own Redis client in any way you wish and pass it via *client* parameter instead of *host*/*port* parameters.

2 - Keep using *host*/*port* parameters but also use *options* parameter. Any kwarg option supported by [Redis-py](https://redis-py.readthedocs.io/en/latest/) can be used there. At a glance, *password* and *username* parameters are what you likely want.

Enjoy

**Comment by brnavneet** [comment]
Thanks a lot! it works. But It would be better to mention it in the document as an example.

**Comment by mlasevich** [comment]
Given this was opened as an issue twice now, you are probably right
